### ISSUE TITLE
docker搭建的，建议把 config.json 里的alist地址增加到 environment 设置，因为默认地址不对，会导致页面打不开。还需要手动修改这个配置文件

### ISSUE THREAD

**Issue by stkroot** [traceless/alist-encrypt#41]

**Comment by stkroot** [comment]
使用docker compose，和alist一起搭建，alist另开端口5254，类似下面这样。就可以一键设置了，这样对新入坑的朋友更友好一点。


docker-compose.yaml 例子
```
version: '3'
services:
  alist-encrypt:
    image: prophet310/alist-encrypt:beta
    restart: unless-stopped
    hostname: alist-encrypt
    container_name: alist-encrypt
    volumes:
      - ./alist-encrypt:/node-proxy/conf
    environment:
      PUID: 1026
      PGID: 100
      TZ: Asia/Shanghai
      ALIST_HOST: 192.168.31.254:5254        # 建议加个设置项，类似这样
    ports:
      - 5344:5344
    network_mode: bridge

  alist-encrypt_dir:
    image: xhofe/alist:latest
    restart: unless-stopped
    hostname: alist-encrypt_dir
    container_name: alist-encrypt_dir
    volumes:
      - ./alist-encryptdir/config:/alist/config
      - ./alist-encryptdir/data:/opt/alist/data
    environment:
      PUID: 1026
      PGID: 100
      TZ: Asia/Shanghai
    ports:
      - 5254:5244
      - 5255:5245
    network_mode: bridge
```
