### ISSUE TITLE
配置 alist url 为 docker service name 会导致查看非加密数据异常

### ISSUE THREAD

**Issue by greatbody** [traceless/alist-encrypt#47]
导致问题的代码：
https://github.com/traceless/alist-encrypt/blob/dfba5606341dd5675a04dbadefba7a53f4188594/node-proxy/app.js#L239-L241

如果 `ctx.req.selfHost` 我们配置的是 docker service 的名字，如下 `ALIST_HOST: alist:5244`

```yaml
version: '3.3'
services:
  alist:
    image: 'xhofe/alist:latest'
    restart: always
    volumes:
      - '/etc/alist:/opt/alist/data'
    ports:
      - '5244:5244'
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
    container_name: alist
  alist-encrypt:
    image: prophet310/alist-encrypt:beta
    restart: unless-stopped
    container_name: alist-encrypt
    volumes:
      - ./alist-encrypt:/node-proxy/conf
    environment:
      TZ: Asia/Shanghai
      ALIST_HOST: alist:5244        # 建议加个设置项，类似这样
    ports:
      - '5344:5344'
```

就会导致在预处理非加密文件的展示的时候，网址被替换为

<img width="528" alt="image" src="https://github.com/traceless/alist-encrypt/assets/6984599/b3e83e8a-fc91-4600-8f68-c6d8e4eb6341">

很容易注意到我们这浏览器中，用到了仅仅可以在 docker 网络中用的 hostname。这会导致我们的浏览器无法正确显示。

# 问题出现的原因

作者的目的是在相应非加密数据的时候，尽量不代理，走原 alist。但是意外导致了这个问题。
